New templates
stravalib/stravalib pull request #410
Opened 2023-08-16 18:01 UTC by lwasser

closes #issue-this-closes-here

*The text above will ensure the issue will be closed when this PR is merged*

## Description

## Type of change

Select the statement best describes this pull request.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This is a documentation update
- [ ] Other (please describe)

## Does your PR include tests

If you are fixing a bug or adding a feature, we appreciate (but do not require)
tests to support whatever fix of feature you're implementing.

- [ ] Yes
- [ ] No, i'd like some help with tests
- [ ] This change doesn't require tests

## Did you include your contribution to the change log?

- [ ] Yes, `changelog.md` is up-to-date.

*If you are having a hard time getting the tests to run correctly feel free to
ping one of the maintainers here!*

2023-08-16 18:09 UTC, lwasser commented on .github/ISSUE_TEMPLATE/documentation-issue.yml
> +name:  📝 Documentation Improvement :smi
```suggestion
name:  📝 Documentation Improvement
```

2023-08-16 18:11 UTC, lwasser commented
ok friends - [have a look here to test these out in my repo](https://github.com/lwasser/stravalib/issues/new/choose) - let me know if you catch any issues / typos or want additional features. i decided to turn these into forms and added a config to direct folks to our discussions for general questions vs bug or documentation reports. CI will likely yell at us for poor test coverage but that doesn't relate to this issue!!

2023-08-17 08:08 UTC, enadeau requested changes
I globally really likes the template, only left two small comments.

I'm also thinking whether we should have a template for feature request? Or maybe allow blank issue for issue that don't really fit in one of the templates?

2023-08-17 23:45 UTC, lwasser commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Please paste the output of ``pip list`` or ``conda list`` here
ok no problem - i can make that change (likely will be in the next few days!)... i'll do the same with conda

`conda env export > environment.yml` for easier reproducibility!

2023-08-17 23:47 UTC, lwasser commented on .github/ISSUE_TEMPLATE/documentation-issue.yml
> +            of stravalib.
oh gosh - that is a mistake.  i'll fix. i must have overwritten something while rebasing or something? 🤷‍♀️ i was using the [pandas templates](https://raw.githubusercontent.com/pandas-dev/pandas/main/.github/ISSUE_TEMPLATE/documentation_improvement.yaml) which are nice. there should only be one box to ensure they are building docs or looking at docs from main.

2023-08-17 23:48 UTC, lwasser commented
thank you all for the feedback!! 🚀  i'll make a few changes in the next few days so we can merge these and the nox pr!

2023-08-21 00:36 UTC, lwasser commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        Please paste the output of ``pip list`` or ``conda list`` here
just pushed a fix for this

2023-08-21 00:36 UTC, lwasser commented on .github/ISSUE_TEMPLATE/documentation-issue.yml
> +            of stravalib.
this was pushed as well. i haven't merged either fix into my main branch - YET for testing but will

2023-08-21 00:46 UTC, lwasser commented
ok friends, [you can view the updates here](https://github.com/lwasser/stravalib/issues/new/choose) 
below is a screenshot. i enabled empty issues just in case as an option. 

<img width="1510" alt="Screen Shot 2023-08-20 at 6 45 59 PM" src="https://github.com/stravalib/stravalib/assets/7649194/b9f09728-8422-4e5b-84df-3840dfc21d22">

Let me know if you catch anything else!!

2023-08-21 00:50 UTC, lwasser commented
Ok ready for review!! 

> Nice work very helpful

thank you @yihong0618 !!

2023-08-21 15:25 UTC, lwasser commented
ok great - with two reviews i'm going to merge this. Jonatan is super busy this week but we can always revisit in the future if we need to make changes!! thank you @yihong0618 and @enadeau for the reviews!!

2023-08-21 15:25 UTC, merged